### ISSUE TITLE
Access Token and Refresh Token Secrets being leaked in Github Action Logs and publicly visible to anyone

### ISSUE THREAD

**Issue by somethingnew2-0** [ericanastas/deploy-google-app-script-action#1]
Because the `CLASPRC_JSON_FILE` environment variable is not a repository secret it is being leaked during some of the Github Action deployment steps including "Push script to scripts.google.com" and "Deploy Script"

For example, this is what I see in my logs (I've partially redacted with ...):
```
Run clasp push -f
  clasp push -f
  shell: /usr/bin/bash -e {0}
  env:
    CLASPRC_JSON_FILE: CLASPRC_JSON_FILE: {"token":{"access_token":"ya29.a0AR..........
    CLASPRC_JSON_SECRET: ***
```

Also, [I can currently see secrets in your repository being leaked ](https://github.com/ericanastas/deploy-google-app-script-action/runs/3916372870?check_suite_focus=true)in the "Save updated CLASPRC_JSON environment variable to CLASPRC_JSON repo secret" deploy step (I've redacted them in this issue with ....):
```
Run hmanzur/actions-set-secret@v2.0.0
  with:
    name: CLASPRC_JSON
    value: {"token":{"access_token":"ya29.a0AR...........................","scope":"https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/cloud-platform openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/userinfo.profile","token_type":"Bearer","id_token":"***","expiry_date":1634433630178,"refresh_token":"........................"},"oauth2ClientSettings":{"clientId":"1072944905499-vm2v2i5dvn0a0d2o4ca36i1vge8cvbn0.apps.googleusercontent.com","clientSecret":".............","redirectUri":"http://localhost"},"isLocalCreds":false}
    repository: ericanastas/deploy-google-app-script-action
    token: ***
  env:
    CLASPRC_JSON_FILE: {"token":{"access_token":"ya29.a0AR.........","scope":"https://www.googleapis.com/auth/script.webapp.deploy https://www.googleapis.com/auth/script.projects https://www.googleapis.com/auth/drive.metadata.readonly https://www.googleapis.com/auth/logging.read https://www.googleapis.com/auth/cloud-platform openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/script.deployments https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/service.management https://www.googleapis.com/auth/userinfo.profile","token_type":"Bearer","id_token":"***","expiry_date":1634433630178,"refresh_token":"................."},"oauth2ClientSettings":{"clientId":"1072944905499-vm2v2i5dvn0a0d2o4ca36i1vge8cvbn0.apps.googleusercontent.com","clientSecret":"..............","redirectUri":"http://localhost"},"isLocalCreds":false}
    CLASPRC_JSON_SECRET: ***
```

**Comment by somethingnew2-0** [comment]
Sorry for the delay, yes that's looking better.  One thing to add, maybe `CLASPRC_JSON_FILE` with `{}` as value should be recommended to be added as a repository secret in the README.md so that it is automatically masked in the logs?

**Comment by ericanastas** [comment]
@somethingnew2-0 

I don't think the automatic masking works by matching the secret names with environment variable names. Creating a `CLASPRC_JSON_FILE` secret is not going to mask anything unless it is somehow also had the new value.

For example say a repo has a secret named `SECRET_A` with the value "123" and the following action is run.

```yaml
name: Test Secret Masking

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Secret
        id: echo-secret
        run: echo "$SECRET_B"
        env:
          SECRET_B: ${{ secrets.SECRET_A }}
          #SECRET_A is set to "123" in repository
      - name: Echo 123
        id: echo-1232
        run: echo "123"
```

This generates the following log

```
Echo Secret
Run echo "$SECRET_B"
  echo "$SECRET_B"
  shell: /usr/bin/bash -e {0}
  env:
    SECRET_B: ***
***
Echo ***
Run echo "***"
  echo "***"
  shell: /usr/bin/bash -e {0}
***
```

The log masks the secret value "123" anywhere it is found. It doesn't matter if my environment variable is named `SECRET_B` and not `SECRET_A`. The secret value is identified and masked according it the actual value of the secret.
